apiVersion: v1
kind: Service
metadata:
  name: dnsseeder-udp
  namespace: default
  annotations:
    cloud.google.com/network-tier: Standard
spec:
  ports:
    - protocol: UDP
      port: 53
      targetPort: 8053
  selector:
    service: dnsseeder
  type: LoadBalancer
  externalTrafficPolicy: Local
  loadBalancerIP: 35.208.20.176
